services:
    gorgo_datagrid_debug.manager.debug:
        class: 'Gorgo\Bundle\DatagridDebugBundle\Manager\DatagridDebugManager'
        arguments:
            - '@oro_datagrid.configuration.provider'

#    gorgo_datagrid_debug.services:
#        class: 'Symfony\Component\DependencyInjection\ParameterBag\ParameterBag'
#        calls:
#            - ['set', ['oro_datagrid.configuration.provider','@oro_datagrid.configuration.provider']]
